-- Databricks notebook source
-- MAGIC %md
-- MAGIC
-- MAGIC <div style="text-align: center; line-height: 0; padding-top: 9px;">
-- MAGIC   <img
-- MAGIC     src="https://databricks.com/wp-content/uploads/2018/03/db-academy-rgb-1200px.png"
-- MAGIC     alt="Databricks Learning"
-- MAGIC   >
-- MAGIC </div>
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Demo - Create a Simple Metric View
-- MAGIC
-- MAGIC In this demonstration we will start with a fact table and build a basic metric view from it.
-- MAGIC
-- MAGIC ### Estimated Duration: 10 minutes
-- MAGIC
-- MAGIC ### Learning Objectives
-- MAGIC
-- MAGIC By the end of this lesson, you should be able to:
-- MAGIC - Create a simple metric view using the Catalog Explorer UI given a YAML definition.
-- MAGIC - Create another metric using a natural language prompt with Databricks Assistant.
-- MAGIC - Create another metric by embedding YAML in SQL DDL.
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## REQUIRED - SELECT A SHARED SQL WAREHOUSE
-- MAGIC
-- MAGIC Before executing cells in this notebook, please select the **SHARED SQL WAREHOUSE** in the lab. Follow these steps:
-- MAGIC
-- MAGIC 1. Navigate to the top-right of this notebook and click the drop-down to select compute (it might say **Connect**). Complete one of the following below:
-- MAGIC
-- MAGIC    a. Under **Recent resources**, check to see if you have a **shared_warehouse SQL**. If you do, select it.
-- MAGIC
-- MAGIC    b. If you do not have a **shared_warehouse** under **Recent resources**, complete the following:
-- MAGIC
-- MAGIC     - In the same drop-down, select **More**.
-- MAGIC
-- MAGIC     - Then select the **SQL Warehouse** button.
-- MAGIC
-- MAGIC     - In the drop-down, make sure **shared_warehouse** is selected.
-- MAGIC
-- MAGIC     - Then, at the bottom of the pop-up, select **Start and attach**.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## A. Classroom Setup
-- MAGIC
-- MAGIC 1. Run the following cell to configure your working environment for this notebook.
-- MAGIC
-- MAGIC **NOTE:** The `DA` object is only used in Databricks Academy courses and is not available outside of these courses. It will dynamically reference the information needed to run the course in your environment.

-- COMMAND ----------

-- MAGIC %run ./Includes/1-Classroom-Setup

-- COMMAND ----------

-- MAGIC %md
-- MAGIC 2. Run the following cell to view your default catalog and schema. Confirm that your default schema is `labuser` followed by a sequence of digits, such as **labuser11089101_1757916624** and your catalog is **default**.
-- MAGIC

-- COMMAND ----------

-- Change the default catalog/schema
USE CATALOG IDENTIFIER(DA.catalog_name);
USE SCHEMA default;

-- View current catalog and schema
SELECT current_catalog(), current_schema()

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## B. Explore the Sample Data using the Databricks UI's Catalog view
-- MAGIC
-- MAGIC 1. In the Databricks UI, click on Catalog and  navigate through the **samples** catalog into the **tpch** schema. It consists of several related tables. Examine the **lineitem** table by clicking it and then choosing the Sample Data tab. One of the fields is **l_orderkey**. This is a foreign key. 
-- MAGIC
-- MAGIC 1. Now navigate to the **orders** table and choose the Sample Data tab. The **orders** table contains records where these **l_orderkey** values are the primary key. Because each order consists of multiple items, there is a one-to-many relationship between rows in the **orders** table and rows in the **lineitem** table.
-- MAGIC
-- MAGIC Notice that each record in the **orders** table contains a foreign key **o_custkey**
-- MAGIC
-- MAGIC 3. Now navigate to the **customer** table and choose the Sample Data tab. As you would expect the **customer** table contains records where these customer IDs are the primary key. Each record in **customer** contains a (fictitious) customer name and address.
-- MAGIC
-- MAGIC 1. Navigate back to the **orders** table. Notice that each order record contains a foreign key, **l\_orderkey**, that points into the **lineitem** table. There is a one-to-many relationship between order records and lineitem records, because each order consists of one or more products.
-- MAGIC
-- MAGIC 1. Let's find out how many records are there in the **lineitem** table.  Choose SQL Editor from the left navigation in the Databricks UI and enter this query:
-- MAGIC
-- MAGIC ```
-- MAGIC SELECT COUNT(*) AS `Row Count` 
-- MAGIC FROM samples.tpch.lineitem ;
-- MAGIC ```
-- MAGIC
-- MAGIC You should find that there are just under 30 million. 
-- MAGIC
-- MAGIC 6. Over what years are these records distributed? Choose SQL Editor from the left navigation in the Databricks UI and enter this query:
-- MAGIC
-- MAGIC ```
-- MAGIC SELECT DISTINCT YEAR(o_orderdate) AS `Order Year` 
-- MAGIC FROM samples.tpch.orders
-- MAGIC ORDER BY `Order Year`;
-- MAGIC ```
-- MAGIC
-- MAGIC Filtering this table by year will reduce the amount of data our queries process.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## C. Create a Metric View Using the Databricks UI
-- MAGIC
-- MAGIC ### C1. Define the Metric View's Basic Details
-- MAGIC
-- MAGIC 1. Right click on **Catalog** in the main navigation bar and select **Open Link in New Tab** to open **Catalog Explorer**.
-- MAGIC
-- MAGIC 1. In **Catalog Explorer**, navigate to **samples.tpch.lineitem**, the table to use as the fact table for the metric view. 
-- MAGIC
-- MAGIC 1. Select the **Create** button at top right and select **Metric View**. 
-- MAGIC
-- MAGIC 1. Use the dropdowns for catalog and schema at the top left of the panel to place the metric view you are building in the catalog with name beginning with `labuser` and the **default** schema .
-- MAGIC
-- MAGIC 1. If the user interface brings up the Databricks Assistant chat window, close it for now.
-- MAGIC
-- MAGIC 1. Click on the proposed name of the metric view, which contains the name of the base table, and change it to **order_details**.
-- MAGIC
-- MAGIC 1. You will see a skeletal metric view YAML file in the editor window, consisting of these sections:
-- MAGIC
-- MAGIC | Section | Meaning |
-- MAGIC |----|----|
-- MAGIC | **version** | Databricks's version of the metric-view specification |
-- MAGIC | **source** | the fact table for this metric view |
-- MAGIC
-- MAGIC **CAUTION**: If the user interface proposed sections for you other than these two, delete them for now. 
-- MAGIC
-- MAGIC The first line of the skeleton metric view should read
-- MAGIC
-- MAGIC ```
-- MAGIC version: 1.1
-- MAGIC ```
-- MAGIC
-- MAGIC If not, change the line so that it does.
-- MAGIC
-- MAGIC **NOTE**: The lab exercises in this course were designed to work with version 1.1 of the metric views API. If the sample metric view proposed for you by the user interface starts with a different number, Databricks has introduced a new version of the API since this course was released. However, specifying version 1.1 in your metric views in this course will ensure that the lab exercises continue to work as intended. 
-- MAGIC
-- MAGIC 8. The next line identifies the fact table you chose to build this metric view on:
-- MAGIC
-- MAGIC ```
-- MAGIC source: samples.tpch.lineitem
-- MAGIC ```
-- MAGIC
-- MAGIC 9. If the UI proposed a number of sample dimensions and measures for you, delete them for now. Delete all the suggested measures by highlighting them and cutting.
-- MAGIC
-- MAGIC 10. Add a **joins** section with joins that bring in enriching data for the fact table. Insert the following below **source**:
-- MAGIC
-- MAGIC ```
-- MAGIC joins:
-- MAGIC    - name: orders
-- MAGIC      source: samples.tpch.orders
-- MAGIC      on: orders.o_orderkey = source.l_orderkey
-- MAGIC      joins:
-- MAGIC      - name: customers
-- MAGIC        source: samples.tpch.customer
-- MAGIC        on: orders.o_custkey = customers.c_custkey
-- MAGIC ```
-- MAGIC
-- MAGIC Make sure to get the indentation exactly as shown. Use spaces, not tabs.
-- MAGIC
-- MAGIC **BEST PRACTICE**: Always look for opportunities to focus the rows returned by a metric view on what your audience of data consumers needs. Don't count on the use of WHERE clauses when the metric view is queried. Instead, proactively limit what is returned to what your business needs using the `filter` clause.
-- MAGIC
-- MAGIC 11. Add a filter, so that we can reduce the cost of this metric view by limiting the number of rows it will return. Insert this line, without any indentation, just below the source section, above the **joins** keyword.
-- MAGIC
-- MAGIC ```
-- MAGIC filter: YEAR(orders.o_orderdate) > 1994
-- MAGIC ```
-- MAGIC
-- MAGIC 12. Now add some measures. Remember that a measure is an indicator of business activity, in terms our data consumers understand, independently of how that indicator is grouped or sliced. Insert a `measures:` keyword, on a new line at the end of the file, so that it comprises a new  **measures** section, and then some measure definitions:
-- MAGIC
-- MAGIC ```
-- MAGIC measures:
-- MAGIC   - name: total_item_count
-- MAGIC     expr: COUNT(source.l_orderkey)
-- MAGIC     display_name: Total Item Count
-- MAGIC   - name: total_distinct_orders
-- MAGIC     expr: COUNT(DISTINCT source.l_orderkey)
-- MAGIC     display_name: Total Distinct Orders
-- MAGIC ```
-- MAGIC
-- MAGIC 13. Now add some dimensions. Remember that a dimension is a way to slice or group the offered measures; the selection of dimensions is driven by the needs of the business. For example, if your data consumers make decisions based on quarterly data, you would choose to offer dimensions based on quarters. Insert a `dimensions:` keyword, on a new line at the end of the file, so that it comprises a new  **dimensions** section, and then some measure definitions:
-- MAGIC
-- MAGIC ```
-- MAGIC dimensions:
-- MAGIC   - name: order_ID
-- MAGIC     expr: orders.o_orderkey
-- MAGIC     display_name: Order ID
-- MAGIC   - name: order_date
-- MAGIC     expr: orders.o_orderdate
-- MAGIC     display_name: Order Date
-- MAGIC   - name: shipping_mode
-- MAGIC     expr: source.l_shipmode
-- MAGIC     display_name: Shipping Mode
-- MAGIC
-- MAGIC ```
-- MAGIC
-- MAGIC **BEST PRACTICE**: Name your dimensions and measures to make them clear and meaningful for your data consumers, NOT for the data and AI team. Assume that dimension and measure names will be seen by non-technical business data consumers who do not know or care about how your Databricks estate is implemented. 
-- MAGIC
-- MAGIC **BEST PRACTICE**: For each measure and dimension, supply a **name** that is easy to work with in code and expression contexts (for example, not including spaces or parentheses), and also a **display_name** that is ideal for use in dashboards or other presentation modes.
-- MAGIC
-- MAGIC **NOTE**: There is no requirement for measure and dimension display names to contain spaces, although it's a common practice, in order to make the names consumer-oriented. Their actual names can also contain spaces, although quoting with backticks becomes required in SQL contexts if they do. 
-- MAGIC
-- MAGIC 14. Now click **Save** at top right. If the UI points out any syntax errors, correct them and try again.
-- MAGIC
-- MAGIC 15. When prompted, click **Keep editing** to refine the metric view further.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### C2. Use Databricks Assistant to enhance the metric view
-- MAGIC
-- MAGIC In this section we will let AI propose a new metric for us. We'll check the result and then add it to the metric definition.
-- MAGIC
-- MAGIC 1. Click the Assistant icon at top right and say what you want in Assistant's chat box using natural language:
-- MAGIC
-- MAGIC ```
-- MAGIC Help me add a ship date dimension to the metric view called labuserXXX.default.order_details with a date format
-- MAGIC ```
-- MAGIC
-- MAGIC Replace `labuserXXX` with your provided catalog name.
-- MAGIC
-- MAGIC 2. Assistant replies by finding the field we mean, composing the correct syntax, and offering us an updated version of the YAML file that we can copy and paste over what we have. Instead of taking the whole response, just select the part having to do with the new dimension. 
-- MAGIC
-- MAGIC 3. Accept or paste it into the YAML window. Don't click **Save** yet.
-- MAGIC
-- MAGIC
-- MAGIC #### Checkpoint
-- MAGIC The Databricks Assistant should return something like the following:
-- MAGIC ```yaml
-- MAGIC   - name: ship_date
-- MAGIC     expr: source.l_shipdate
-- MAGIC     display_name: Shipping Date
-- MAGIC     format:
-- MAGIC       type: date
-- MAGIC       date_format: locale_short_month
-- MAGIC       leading_zeros: false
-- MAGIC ```
-- MAGIC
-- MAGIC
-- MAGIC **NOTE**: The assistant may produce different results in the above output.
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### C3. Add semantic tips to your metric view
-- MAGIC
-- MAGIC 1. Look again at the Ship Date and Order Date dimensions you created in previous parts. They should look something like this:
-- MAGIC
-- MAGIC ```
-- MAGIC dimensions:
-- MAGIC   - name: order_date
-- MAGIC     expr: orders.o_orderdate
-- MAGIC     display_name: Order Date
-- MAGIC ...
-- MAGIC   - name: ship_date
-- MAGIC     expr: source.l_shipdate
-- MAGIC     display_name: Shipping Date
-- MAGIC ```
-- MAGIC
-- MAGIC **NOTE**: You added the **Ship Date** dimension with Databricks Assistant's help in the previous part of the lab.
-- MAGIC
-- MAGIC If not, correct your definition so that it matches the above.
-- MAGIC
-- MAGIC 2. Now add some hints for the consistent display of the dates for **order_date** and **ship_date**. Add these lines immediately below each dimension's `display_name`:
-- MAGIC
-- MAGIC ```
-- MAGIC     format:
-- MAGIC       type: date
-- MAGIC       date_format: year_month_day
-- MAGIC       leading_zeros: false
-- MAGIC ```
-- MAGIC
-- MAGIC **NOTE**: It is a common error to introduce a list beneath a `format` specifier by starting lines with hyphens. Instead, the `format` keyword is followed by an indented series of items and values, with no hyphens, as shown here.
-- MAGIC
-- MAGIC
-- MAGIC 3. Visit the other measures and dimensions you added and add `synonym` fields, intended to help future consumers of this metric view understand its semantics. For example, add this to the `order_ID` dimension:
-- MAGIC
-- MAGIC ```
-- MAGIC      synonyms:
-- MAGIC       - order identifier
-- MAGIC       - receipt number
-- MAGIC ```
-- MAGIC
-- MAGIC
-- MAGIC

-- COMMAND ----------

-- MAGIC %md-sandbox
-- MAGIC ##### YAML Checkpoint - ANSWER
-- MAGIC
-- MAGIC **CAUTION**: Before you proceed, confirm that your metric view has two measures and four dimensions. They'll be needed in future steps.
-- MAGIC
-- MAGIC * Dimensions:
-- MAGIC    *  order_ID
-- MAGIC    *  order_date
-- MAGIC    *  shipping_mode
-- MAGIC    *  ship_date
-- MAGIC  * Measures:
-- MAGIC    * total_item_count
-- MAGIC    * total_distinct_orders
-- MAGIC
-- MAGIC Complete the following steps (Optional):
-- MAGIC
-- MAGIC - Set your **LABUSER** catalog and **default** schema
-- MAGIC - Create a metric view named **order_details**
-- MAGIC - Paste the starter YAML into the editor
-- MAGIC - Replace the **LABUSER** placeholder with your own catalog name in all table references
-- MAGIC
-- MAGIC <details>
-- MAGIC   <summary>EXPAND FOR SOLUTION CODE</summary>
-- MAGIC <button onclick="copyBlock()">Copy to clipboard</button>
-- MAGIC
-- MAGIC <pre id="copy-block" style="font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace; border:1px solid #e5e7eb; border-radius:10px; background:#f8fafc; padding:14px 16px; font-size:0.85rem; line-height:1.35; white-space:pre;">
-- MAGIC <code>
-- MAGIC <!-------------------ADD SOLUTION CODE BELOW------------------->
-- MAGIC version: 1.1
-- MAGIC
-- MAGIC source: samples.tpch.lineitem
-- MAGIC
-- MAGIC joins:
-- MAGIC   - name: orders
-- MAGIC     source: samples.tpch.orders
-- MAGIC     "on": orders.o_orderkey = source.l_orderkey
-- MAGIC     joins:
-- MAGIC       - name: customers
-- MAGIC         source: samples.tpch.customer
-- MAGIC         "on": orders.o_custkey = customers.c_custkey
-- MAGIC
-- MAGIC filter: YEAR(orders.o_orderdate) > 1994
-- MAGIC
-- MAGIC dimensions:
-- MAGIC   - name: order_ID
-- MAGIC     expr: orders.o_orderkey
-- MAGIC     display_name: Order ID
-- MAGIC     synonyms:
-- MAGIC     - order identifier
-- MAGIC     - receipt number
-- MAGIC   - name: order_date
-- MAGIC     expr: orders.o_orderdate
-- MAGIC     display_name: Order Date
-- MAGIC     format:
-- MAGIC       type: date
-- MAGIC       date_format: year_month_day
-- MAGIC       leading_zeros: false
-- MAGIC   - name: shipping_mode
-- MAGIC     expr: source.l_shipmode
-- MAGIC     display_name: Shipping Mode
-- MAGIC   - name: ship_date
-- MAGIC     expr: source.l_shipdate
-- MAGIC     display_name: Shipping Date
-- MAGIC     format:
-- MAGIC       type: date
-- MAGIC       date_format: year_month_day
-- MAGIC       leading_zeros: false
-- MAGIC
-- MAGIC measures:
-- MAGIC   - name: total_item_count
-- MAGIC     expr: COUNT(source.l_orderkey)
-- MAGIC     display_name: Total Item Count
-- MAGIC   - name: total_distinct_orders
-- MAGIC     expr: COUNT(DISTINCT source.l_orderkey)
-- MAGIC     display_name: Total Distinct Orders
-- MAGIC <!-------------------END SOLUTION CODE------------------->
-- MAGIC </code></pre>
-- MAGIC
-- MAGIC
-- MAGIC <script>
-- MAGIC function copyBlock() {
-- MAGIC   const el = document.getElementById("copy-block");
-- MAGIC   if (!el) return;
-- MAGIC
-- MAGIC   const text = el.innerText;
-- MAGIC
-- MAGIC   // Preferred modern API
-- MAGIC   if (navigator.clipboard && navigator.clipboard.writeText) {
-- MAGIC     navigator.clipboard.writeText(text)
-- MAGIC       .then(() => alert("Copied to clipboard"))
-- MAGIC       .catch(err => {
-- MAGIC         console.error("Clipboard write failed:", err);
-- MAGIC         fallbackCopy(text);
-- MAGIC       });
-- MAGIC   } else {
-- MAGIC     fallbackCopy(text);
-- MAGIC   }
-- MAGIC }
-- MAGIC
-- MAGIC function fallbackCopy(text) {
-- MAGIC   const textarea = document.createElement("textarea");
-- MAGIC   textarea.value = text;
-- MAGIC   textarea.style.position = "fixed";
-- MAGIC   textarea.style.left = "-9999px";
-- MAGIC   document.body.appendChild(textarea);
-- MAGIC   textarea.select();
-- MAGIC   try {
-- MAGIC     document.execCommand("copy");
-- MAGIC     alert("Copied to clipboard");
-- MAGIC   } catch (err) {
-- MAGIC     console.error("Fallback copy failed:", err);
-- MAGIC     alert("Could not copy to clipboard. Please copy manually.");
-- MAGIC   } finally {
-- MAGIC     document.body.removeChild(textarea);
-- MAGIC   }
-- MAGIC }
-- MAGIC </script>
-- MAGIC </details>

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## E. (OPTIONAL) Create a metric view using the SQL Editor
-- MAGIC
-- MAGIC It is also possible to make a metric view completely within the SQL Editor, using SQL Data Definition Language.
-- MAGIC
-- MAGIC 1. In the left-hand navigation of the Databricks UI, click on SQL Editor. 
-- MAGIC
-- MAGIC 1. In the top bar of the SQL Editor, choose your assigned catalog (starting with `labuser`) and the `default` schema.
-- MAGIC
-- MAGIC 1. Continue entering code into the SQL Editor window:
-- MAGIC
-- MAGIC ```
-- MAGIC CREATE OR REPLACE VIEW order_details2
-- MAGIC (
-- MAGIC  order_ID,
-- MAGIC  order_date,
-- MAGIC  shipping_mode,
-- MAGIC  ship_date,
-- MAGIC  total_item_count,
-- MAGIC  total_distinct_orders
-- MAGIC )
-- MAGIC ```
-- MAGIC
-- MAGIC 4. Now append the SQL below to your query being composed (*don't hit Run yet*).
-- MAGIC
-- MAGIC ```
-- MAGIC WITH METRICS
-- MAGIC LANGUAGE YAML
-- MAGIC AS $$
-- MAGIC ```
-- MAGIC
-- MAGIC That $$ tells SQL to expect an embedded document. 
-- MAGIC
-- MAGIC 5. Now paste the YAML file from your other window (or from your clipboard if it's still there) immediately below the $$.  *Don't hit Run yet*.
-- MAGIC
-- MAGIC 6. Finally, immediately below what you pasted in insert this:
-- MAGIC ```
-- MAGIC $$ ;
-- MAGIC ```
-- MAGIC
-- MAGIC This second $$ ends the embedded document, and the semicolon is the regular syntax for ending a SQL query.
-- MAGIC
-- MAGIC 7. Now **Run** the query.
-- MAGIC
-- MAGIC 8. Using **Catalog** in the left hand navigation, drill into the **labuserXXX** catalog and the **default** schema. You will see that you now have two metric views defined.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Additional Resources
-- MAGIC
-- MAGIC - [Create a metric view](https://docs.databricks.com/aws/en/metric-views/create)
-- MAGIC - [Syntax reference for views, including metric views](https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-syntax-ddl-create-view)
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC &copy; 2026 Databricks, Inc. All rights reserved. Apache, Apache Spark, Spark, the Spark Logo, Apache Iceberg, Iceberg, and the Apache Iceberg logo are trademarks of the <a href="https://www.apache.org/" target="_blank">Apache Software Foundation</a>.<br/><br/><a href="https://databricks.com/privacy-policy" target="_blank">Privacy Policy</a> | <a href="https://databricks.com/terms-of-use" target="_blank">Terms of Use</a> | <a href="https://help.databricks.com/" target="_blank">Support</a>
