-- Databricks notebook source
-- MAGIC %md
-- MAGIC
-- MAGIC <div style="text-align: center; line-height: 0; padding-top: 9px;">
-- MAGIC   <img
-- MAGIC     src="https://databricks.com/wp-content/uploads/2018/03/db-academy-rgb-1200px.png"
-- MAGIC     alt="Databricks Learning"
-- MAGIC   >
-- MAGIC </div>
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Demo - Define and Use Computed and Composed Measures
-- MAGIC
-- MAGIC In previous demos, we created a simple metric view and queried it. Let's now enhance that metric view with the kinds of more sophisticated dimensions and measures you would use in the real world.
-- MAGIC
-- MAGIC ### Estimated Duration: 10 minutes
-- MAGIC
-- MAGIC ### Learning Objectives
-- MAGIC
-- MAGIC By the end of this lesson, you should be able to:
-- MAGIC - Compose new metric view components from existing ones.
-- MAGIC - Reference dimensions and measures within a metric view.
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## REQUIRED - SELECT A SHARED SQL WAREHOUSE
-- MAGIC
-- MAGIC Before executing cells in this notebook, please select the **SHARED SQL WAREHOUSE** in the lab. Follow these steps:
-- MAGIC
-- MAGIC 1. Navigate to the top-right of this notebook and click the drop-down to select compute (it might say **Connect**). Complete one of the following below:
-- MAGIC
-- MAGIC    a. Under **Recent resources**, check to see if you have a **shared_warehouse SQL**. If you do, select it.
-- MAGIC
-- MAGIC    b. If you do not have a **shared_warehouse** under **Recent resources**, complete the following:
-- MAGIC
-- MAGIC     - In the same drop-down, select **More**.
-- MAGIC
-- MAGIC     - Then select the **SQL Warehouse** button.
-- MAGIC
-- MAGIC     - In the drop-down, make sure **shared_warehouse** is selected.
-- MAGIC
-- MAGIC     - Then, at the bottom of the pop-up, select **Start and attach**.

-- COMMAND ----------

-- MAGIC %md-sandbox
-- MAGIC ##### YAML Checkpoint - ANSWER
-- MAGIC
-- MAGIC If you did not complete the previous notebooks, use the starter YAML metric view provided below.
-- MAGIC
-- MAGIC Complete the following steps:
-- MAGIC
-- MAGIC - Set your **LABUSER** catalog and **default** schema
-- MAGIC - Create a metric view named **order_details**
-- MAGIC - Paste the starter YAML into the editor
-- MAGIC - Replace the **LABUSER** placeholder with your own catalog name in all table references
-- MAGIC
-- MAGIC <details>
-- MAGIC   <summary>EXPAND FOR SOLUTION CODE</summary>
-- MAGIC <button onclick="copyBlock()">Copy to clipboard</button>
-- MAGIC
-- MAGIC <pre id="copy-block" style="font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace; border:1px solid #e5e7eb; border-radius:10px; background:#f8fafc; padding:14px 16px; font-size:0.85rem; line-height:1.35; white-space:pre;">
-- MAGIC <code>
-- MAGIC <!-------------------ADD SOLUTION CODE BELOW------------------->
-- MAGIC version: 1.1
-- MAGIC
-- MAGIC source: samples.tpch.lineitem
-- MAGIC
-- MAGIC joins:
-- MAGIC   - name: orders
-- MAGIC     source: samples.tpch.orders
-- MAGIC     "on": orders.o_orderkey = source.l_orderkey
-- MAGIC     joins:
-- MAGIC       - name: customers
-- MAGIC         source: samples.tpch.customer
-- MAGIC         "on": orders.o_custkey = customers.c_custkey
-- MAGIC
-- MAGIC filter: YEAR(orders.o_orderdate) > 1994
-- MAGIC
-- MAGIC dimensions:
-- MAGIC   - name: order_ID
-- MAGIC     expr: orders.o_orderkey
-- MAGIC     display_name: Order ID
-- MAGIC     synonyms:
-- MAGIC     - order identifier
-- MAGIC     - receipt number
-- MAGIC   - name: order_date
-- MAGIC     expr: orders.o_orderdate
-- MAGIC     display_name: Order Date
-- MAGIC     format:
-- MAGIC       type: date
-- MAGIC       date_format: year_month_day
-- MAGIC       leading_zeros: false
-- MAGIC   - name: shipping_mode
-- MAGIC     expr: source.l_shipmode
-- MAGIC     display_name: Shipping Mode
-- MAGIC   - name: ship_date
-- MAGIC     expr: source.l_shipdate
-- MAGIC     display_name: Shipping Date
-- MAGIC     format:
-- MAGIC       type: date
-- MAGIC       date_format: year_month_day
-- MAGIC       leading_zeros: false
-- MAGIC
-- MAGIC measures:
-- MAGIC   - name: total_item_count
-- MAGIC     expr: COUNT(source.l_orderkey)
-- MAGIC     display_name: Total Item Count
-- MAGIC   - name: total_distinct_orders
-- MAGIC     expr: COUNT(DISTINCT source.l_orderkey)
-- MAGIC     display_name: Total Distinct Orders
-- MAGIC <!-------------------END SOLUTION CODE------------------->
-- MAGIC </code></pre>
-- MAGIC
-- MAGIC
-- MAGIC <script>
-- MAGIC function copyBlock() {
-- MAGIC   const el = document.getElementById("copy-block");
-- MAGIC   if (!el) return;
-- MAGIC
-- MAGIC   const text = el.innerText;
-- MAGIC
-- MAGIC   // Preferred modern API
-- MAGIC   if (navigator.clipboard && navigator.clipboard.writeText) {
-- MAGIC     navigator.clipboard.writeText(text)
-- MAGIC       .then(() => alert("Copied to clipboard"))
-- MAGIC       .catch(err => {
-- MAGIC         console.error("Clipboard write failed:", err);
-- MAGIC         fallbackCopy(text);
-- MAGIC       });
-- MAGIC   } else {
-- MAGIC     fallbackCopy(text);
-- MAGIC   }
-- MAGIC }
-- MAGIC
-- MAGIC function fallbackCopy(text) {
-- MAGIC   const textarea = document.createElement("textarea");
-- MAGIC   textarea.value = text;
-- MAGIC   textarea.style.position = "fixed";
-- MAGIC   textarea.style.left = "-9999px";
-- MAGIC   document.body.appendChild(textarea);
-- MAGIC   textarea.select();
-- MAGIC   try {
-- MAGIC     document.execCommand("copy");
-- MAGIC     alert("Copied to clipboard");
-- MAGIC   } catch (err) {
-- MAGIC     console.error("Fallback copy failed:", err);
-- MAGIC     alert("Could not copy to clipboard. Please copy manually.");
-- MAGIC   } finally {
-- MAGIC     document.body.removeChild(textarea);
-- MAGIC   }
-- MAGIC }
-- MAGIC </script>
-- MAGIC </details>

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## A. Classroom Setup
-- MAGIC
-- MAGIC 1. Run the following cell to configure your working environment for this notebook.
-- MAGIC
-- MAGIC **NOTE:** The `DA` object is only used in Databricks Academy courses and is not available outside of these courses. It will dynamically reference the information needed to run the course in your environment.

-- COMMAND ----------

-- MAGIC %run ./Includes/4-Classroom-Setup

-- COMMAND ----------

-- MAGIC %md
-- MAGIC 2. Run the following cell to view your default catalog and schema. Confirm that your default catalog is `labuser` followed by a sequence of digits, such as **labuser11089101_1757916624** and your schema is **default**.
-- MAGIC

-- COMMAND ----------

-- Change the default catalog/schema
USE CATALOG IDENTIFIER(DA.catalog_name);
USE SCHEMA default;

-- View current catalog and schema
SELECT current_catalog(), current_schema()

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## B. Edit the definition of the metric view
-- MAGIC
-- MAGIC We are going to add some computed measures and dimensions to our metric view called **order_details**. We need to enter the metric view editor in order to enhance it.
-- MAGIC
-- MAGIC 1. In the Databricks UI, choose **Catalog** from the left navigation and navigate into the catalog with name starting with `labuser` and the **default** schema.
-- MAGIC
-- MAGIC 1. Click on the **order_details** metric view, and then click the **Edit** button.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## B1. Add a computed dimension
-- MAGIC
-- MAGIC Let's add a dimension for the year and quarter each order came in during. That way it'll be easier for data consumers to bucketize orders by quarter. We use YEAR() to extract a year number from a date, QUARTER() to give us a number from 1 to 4 based on the calendar quarter of a date, and CONCAT to string it all together, with a dash and a Q to separate them. So each order will have a quarter associated with it, consistently formatted like `1999-Q2`. 
-- MAGIC
-- MAGIC 1. In the metric-view definition editor, add this at the end of the **dimensions** section.
-- MAGIC
-- MAGIC
-- MAGIC ```
-- MAGIC - name: order_year_quarter
-- MAGIC   expr: CONCAT(YEAR(orders.o_orderdate), '-Q', QUARTER(orders.o_orderdate))
-- MAGIC ```
-- MAGIC
-- MAGIC Here we  clarify what table the o_orderdate field is in by prepending `orders` to it. This identifier works because **orders** was defined as a source in this YAML file. 
-- MAGIC
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## B2. Create a more sophisticated dimension
-- MAGIC
-- MAGIC Let's also make the contents of the raw data more transparent for human users. Notice that each order has an order status, which is either O for open, P for processing, or F for final. Let's replace those single-letter abbreviations with a word that fully declares the order status.
-- MAGIC
-- MAGIC 1. In the metric-view definition editor, add this at the end of the **dimensions** section (taking care to indent properly).
-- MAGIC
-- MAGIC ```
-- MAGIC   - name: Order Status
-- MAGIC     expr: |
-- MAGIC           CASE
-- MAGIC             WHEN orders.o_orderstatus = "O" THEN "Open"
-- MAGIC             WHEN orders.o_orderstatus = "P" THEN "Processing"
-- MAGIC             WHEN orders.o_orderstatus = "F" THEN "Final"
-- MAGIC             ELSE "Error"
-- MAGIC           END
-- MAGIC ```
-- MAGIC
-- MAGIC The pipe sign in the expression is one of YAML's ways to introduce a muilti-line string value, in this case a SQL CASE expression. We could put the whole expression on one line, but then it would be harder to read. 
-- MAGIC
-- MAGIC Notice that the case clause contains an ELSE so that the expression will never silently return a null value.
-- MAGIC
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## B3. Create a Composed Dimension
-- MAGIC
-- MAGIC Defining dimensions in terms of others makes your logic clearer and easier to maintain. Suppose we wanted to create a dimension for how long it is taking us to ship each order. The business doesn't care about the exact number of days, but rather whether the range meets policy. Shipments between 0 and 2 days after receipt of the order are policy-compliant, while shipments between 2 and 4 days are exceptions, and anything longer is a serious problem we want to address.
-- MAGIC
-- MAGIC The naive way to do that would be this:
-- MAGIC
-- MAGIC ```
-- MAGIC   - name: order_delay_bucket
-- MAGIC     comment: Too much repeated code; also risks introducing nulls
-- MAGIC     expr: |
-- MAGIC           CASE
-- MAGIC              WHEN DATEDIFF(source.l_shipdate,orders.o_orderdate) BETWEEN 0 AND 2 THEN "0-2 days"
-- MAGIC              WHEN DATEDIFF(source.l_shipdate,orders.o_orderdate) BETWEEN 2 AND 4 THEN "2-4 days"
-- MAGIC              ELSE "5+ days"
-- MAGIC           END
-- MAGIC ```
-- MAGIC
-- MAGIC The repeated code in this approach is an opportunity for error. Let's take a clearer, two-step approach.
-- MAGIC
-- MAGIC 1. In the metric-view definition editor, add this at the end of the **dimensions** section (taking care to indent properly).
-- MAGIC
-- MAGIC ```
-- MAGIC      - name: order_delay
-- MAGIC        expr: DATEDIFF(source.l_shipdate,orders.o_orderdate)
-- MAGIC        display_name: Order Delay in Days
-- MAGIC ```
-- MAGIC
-- MAGIC 2. Now add this new dimension immediately below the previous one (taking care to indent properly):
-- MAGIC
-- MAGIC ```
-- MAGIC     - name: order_delay_status
-- MAGIC       expr: |
-- MAGIC             CASE
-- MAGIC                WHEN order_delay < 0 THEN "Item Shipped Before Order!"
-- MAGIC                WHEN order_delay BETWEEN 0 AND 2 THEN "0-2 days"
-- MAGIC                WHEN order_delay BETWEEN 2 AND 4 THEN "2-4 days"
-- MAGIC                ELSE "5+ days"
-- MAGIC             END
-- MAGIC       display_name: Order Delay Status
-- MAGIC ```
-- MAGIC
-- MAGIC
-- MAGIC What could happen if we omitted the clause for **Order Delay** being less than zero?

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## B4. Define Computed and Composed Measures
-- MAGIC
-- MAGIC Metric views provide a focal point for data professionals to drive auditing and agreement. By defining complex measures here, in the metric view, we can make it easy for the whole business to adopt those definitions.
-- MAGIC
-- MAGIC 1. Add this to the end of the **measures** section (taking care to indent properly):
-- MAGIC
-- MAGIC ```
-- MAGIC   - name: revenue_less_discounts
-- MAGIC     expr: SUM(source.l_extendedprice * (1 - source.l_discount))
-- MAGIC     display_name: Total Revenue Less Discounts ($)
-- MAGIC
-- MAGIC ```
-- MAGIC
-- MAGIC If everyone agrees to use this measure as the basis for all profit computations, no one will ever forget to subtract the discounts.
-- MAGIC
-- MAGIC 2. Add this immediately below the previous measure (taking care to indent properly):
-- MAGIC
-- MAGIC ```
-- MAGIC   - name: average_discount_pct
-- MAGIC     expr: AVG(source.l_discount)
-- MAGIC     display_name: Average Discount (%)
-- MAGIC     format:
-- MAGIC       type: percentage
-- MAGIC       decimal_places: 
-- MAGIC         type: exact
-- MAGIC         places: 2 
-- MAGIC ```
-- MAGIC
-- MAGIC Now discount percentages will displayed to the nearest 2 decimal places in contexts downstream from this metric view.
-- MAGIC
-- MAGIC 3. Here is a technique you can use to count the occurrences of phenomena in your data and compute percentages. Let's say you want a metric that shows the rate at which items were returned. Returned items are marked with a value of **R** in the `l_returnflag` field. It's easy to count all records, with the familiar SQL expression `COUNT(*)`, but how can we count only those records marked as returned?
-- MAGIC
-- MAGIC Add this to the end of your `measures` section (taking care to indent properly).
-- MAGIC
-- MAGIC
-- MAGIC ```
-- MAGIC   - name: item_return_rate_pct
-- MAGIC     expr: |
-- MAGIC           SUM(CASE WHEN source.l_returnflag = 'R' 
-- MAGIC                    THEN 1
-- MAGIC                    ELSE 0
-- MAGIC               END) 
-- MAGIC           / COUNT(*)
-- MAGIC     display_name: Item Return Rate (%)
-- MAGIC     format:
-- MAGIC       type: percentage
-- MAGIC       decimal_places: 
-- MAGIC         type: exact
-- MAGIC         places: 2
-- MAGIC
-- MAGIC ```
-- MAGIC
-- MAGIC 4. Save the definition of the metric view.
-- MAGIC
-- MAGIC 1. The business considers any order from which more than half the items were returned to be a sales management problem. Let's use our newly defined measure in a query. Navigate to the SQL Editor and enter this query:
-- MAGIC
-- MAGIC 1. Select the labuser catalog and the default schema to execute the query in the SQL editor.
-- MAGIC
-- MAGIC ```
-- MAGIC  SELECT
-- MAGIC   order_ID,
-- MAGIC   MEASURE(item_return_rate_pct) AS `Item Return Rate %`
-- MAGIC FROM order_details
-- MAGIC GROUP BY order_ID
-- MAGIC HAVING MEASURE(item_return_rate_pct) > 50
-- MAGIC ORDER BY order_ID;
-- MAGIC ```
-- MAGIC
-- MAGIC
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Additional Resources
-- MAGIC
-- MAGIC - [Composability in metric views](https://docs.databricks.com/aws/en/metric-views/data-modeling/composability) 
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC &copy; 2026 Databricks, Inc. All rights reserved. Apache, Apache Spark, Spark, the Spark Logo, Apache Iceberg, Iceberg, and the Apache Iceberg logo are trademarks of the <a href="https://www.apache.org/" target="_blank">Apache Software Foundation</a>.<br/><br/><a href="https://databricks.com/privacy-policy" target="_blank">Privacy Policy</a> | <a href="https://databricks.com/terms-of-use" target="_blank">Terms of Use</a> | <a href="https://help.databricks.com/" target="_blank">Support</a>
