-- Databricks notebook source
-- MAGIC %md
-- MAGIC
-- MAGIC <div style="text-align: center; line-height: 0; padding-top: 9px;">
-- MAGIC   <img
-- MAGIC     src="https://databricks.com/wp-content/uploads/2018/03/db-academy-rgb-1200px.png"
-- MAGIC     alt="Databricks Learning"
-- MAGIC   >
-- MAGIC </div>
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Optional Lab - Summative Experience
-- MAGIC
-- MAGIC In this optional lab exercise, you'll bring together the contents of the entire course, from the scoping of metric views through their creation and consumption.
-- MAGIC
-- MAGIC ### Estimated Duration: 30-45 minutes
-- MAGIC
-- MAGIC ### Learning Objectives
-- MAGIC
-- MAGIC By the end of this lesson, you should be able to:
-- MAGIC - Map from business requirements to metric views that support the business
-- MAGIC - Use the SQL editor to show metadata, hierarchies, and other model details
-- MAGIC - Monitor metric usage and performance
-- MAGIC - Create alerts on metric views using the UI
-- MAGIC - Manage and monitor alerts
-- MAGIC
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## REQUIRED - SELECT A SHARED SQL WAREHOUSE
-- MAGIC
-- MAGIC Before executing cells in this notebook, please select the **SHARED SQL WAREHOUSE** in the lab. Follow these steps:
-- MAGIC
-- MAGIC 1. Navigate to the top-right of this notebook and click the drop-down to select compute (it might say **Connect**). Complete one of the following below:
-- MAGIC
-- MAGIC    a. Under **Recent resources**, check to see if you have a **shared_warehouse SQL**. If you do, select it.
-- MAGIC
-- MAGIC    b. If you do not have a **shared_warehouse** under **Recent resources**, complete the following:
-- MAGIC
-- MAGIC     - In the same drop-down, select **More**.
-- MAGIC
-- MAGIC     - Then select the **SQL Warehouse** button.
-- MAGIC
-- MAGIC     - In the drop-down, make sure **shared_warehouse** is selected.
-- MAGIC
-- MAGIC     - Then, at the bottom of the pop-up, select **Start and attach**.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## A. Classroom Setup
-- MAGIC
-- MAGIC 1. Run the following cell to configure your working environment for this notebook.
-- MAGIC
-- MAGIC **NOTE:** The `DA` object is only used in Databricks Academy courses and is not available outside of these courses. It will dynamically reference the information needed to run the course in your environment.

-- COMMAND ----------

-- MAGIC %run ./Includes/7-Classroom-Setup

-- COMMAND ----------

-- MAGIC %md
-- MAGIC 2. Run the following cell to view your default catalog and schema. Confirm that your default schema is `labuser` followed by a sequence of digits, such as **labuser11089101_1757916624** and your catalog is **default**.
-- MAGIC

-- COMMAND ----------

-- Change the default catalog/schema
USE CATALOG IDENTIFIER(DA.catalog_name);
USE SCHEMA default;

-- View current catalog and schema
SELECT current_catalog(), current_schema()

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## B. Thought exercise: your own organization's measures and dimensions
-- MAGIC
-- MAGIC The process of building a metric view always begins with the needs of the business. Take a few moments and jot down some notes about yours. Please do not share proprietary or confidential information; if you like, use your own laptop or phone to answer the questions here.
-- MAGIC
-- MAGIC #### What are your organization's Key Performance Indicators? (Examples: sales, revenue, profit)
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC
-- MAGIC #### For each of these indicators, what are the axes along which the business needs to see it sliced? (Examples: date, product line, geography)
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC
-- MAGIC
-- MAGIC #### For each of these axes, what are the granularities at which the business needs visibility? (Examples: yearly, quarterly, daily)
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC
-- MAGIC
-- MAGIC #### What novel problems or challenges would you like a metric view to shed clarity on?
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC <br/>
-- MAGIC &nbsp;
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## C. Designing measures and dimensions for a fictitious organization
-- MAGIC
-- MAGIC In this lab activity, we will create a metric view, an AI/BI Dashboard, and an AI/BI Genie space to help a multi-national sales organization track its performance. 
-- MAGIC
-- MAGIC Start by reading how this organization answered the questions above.
-- MAGIC
-- MAGIC **NOTE**: This is a fictitious organization, not any specific Databricks customer. The data is synthetic.
-- MAGIC
-- MAGIC #### What are your organization's Key Performance Indicators? (Examples: sales, revenue, profit)
-- MAGIC
-- MAGIC We track sales revenue and sales item volume.
-- MAGIC
-- MAGIC #### For each of these indicators, what are the axes along which the business needs to see it sliced? (Examples: date, product line, geography)
-- MAGIC
-- MAGIC We slice up our KPIs by date and geography (specifically down to the state or province level).
-- MAGIC
-- MAGIC #### For each of these axes, what are the granularities at which the business needs visibility? (Examples: yearly, quarterly, daily)
-- MAGIC
-- MAGIC We report on quarterly revenue, and within each quarter quarter-to-date. Year-on-year comparisons are also important, although not for years earlier than 2023.
-- MAGIC
-- MAGIC #### What novel problems or challenges would you like a metric view to shed clarity on?
-- MAGIC
-- MAGIC Among our sales force, various sales reps use either of two sales methodologies, because of previous organizational differences. We want to know if results differ between these two methodologies.
-- MAGIC
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## D. Explore the Data using the Databricks UI's Catalog view
-- MAGIC
-- MAGIC We care about our organization's sales results in Australia and Canada. For each, we have a schema containing order history. 
-- MAGIC
-- MAGIC 1. In the Databricks UI, click on Catalog and  navigate through the **dbacademy_australia** catalog into the **v01** schema. It consists of several related tables. Examine the **lineitem** table by clicking it and then choosing the Sample Data tab. One of the fields is **customerid**. This is a foreign key. 
-- MAGIC
-- MAGIC 1. Now navigate to the **customers** table and choose the Sample Data tab. As you would expect the **customers** table contains records where these customer IDs are the primary key. Each record in **customers** contains a (fictitious) customer name and address.
-- MAGIC
-- MAGIC 1. Navigate back to the **orders** table. Notice that each order record contains a sales rep's name. In this scenario, we know the sales methodology employed by each sales rep, both in the Australian organization and in the Canadian organization. 
-- MAGIC
-- MAGIC 1. Let's find out how many records are there in the **orders** table.  Choose SQL Editor from the left navigation in the Databricks UI and enter and run this query:
-- MAGIC
-- MAGIC ```
-- MAGIC SELECT COUNT(*) AS `Row Count` 
-- MAGIC FROM dbacademy_australia.v01.orders ;
-- MAGIC ```
-- MAGIC
-- MAGIC You should find that there are just over 5000. 
-- MAGIC
-- MAGIC 5. Over what years are these records distributed? In the SQL Editor,  enter and run this query:
-- MAGIC
-- MAGIC ```
-- MAGIC SELECT DISTINCT YEAR(orderdate) AS `Order Year` 
-- MAGIC FROM dbacademy_australia.v01.orders
-- MAGIC ORDER BY `Order Year`;
-- MAGIC ```
-- MAGIC
-- MAGIC Recall that this organization said that it doesn't need to do year-on-year comparisons for years earlier than 2023. So we can increase efficiency of a metric view by filtering out sales records earlier than 2022.
-- MAGIC
-- MAGIC 6. Let's display a list of the Australian sales reps. In the SQL Editor,  enter and run this query:
-- MAGIC
-- MAGIC ```
-- MAGIC SELECT salesrep AS `Sales Rep`,
-- MAGIC       SUM(orderamt) AS `Sales Achievement` 
-- MAGIC FROM dbacademy_australia.v01.orders
-- MAGIC GROUP BY `Sales Rep` 
-- MAGIC ORDER BY `Sales Achievement`;
-- MAGIC ```
-- MAGIC
-- MAGIC 7. Repeat these steps with the table **dbacademy_canada.v01.orders** .
-- MAGIC Are there any sales reps who have worked both geographies?

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## E. Create a New Table with Sales Reps' Methodologies
-- MAGIC
-- MAGIC The sales methodologies used by these reps are codenamed "C" and "S". 
-- MAGIC Let's create a small lookup table showing which reps use which methodology. 
-- MAGIC
-- MAGIC 1. In the SQL Editor, enter and run this query, replacing `labuser` with the name of your assigned schema:
-- MAGIC
-- MAGIC ```
-- MAGIC USE CATALOG labuser ; -- replace with your catalog
-- MAGIC USE SCHEMA DEFAULT ;
-- MAGIC CREATE OR REPLACE TABLE methodologies (
-- MAGIC     salesrep STRING,
-- MAGIC     method CHAR(1)
-- MAGIC );
-- MAGIC INSERT INTO methodologies (salesrep, method)
-- MAGIC VALUES 
-- MAGIC        ("Ethan", "C"),
-- MAGIC        ("Gowoon", "C"),
-- MAGIC        ("Harry", "S"),
-- MAGIC        ("Hannah", "S"),
-- MAGIC        ("Ingrid","S"),
-- MAGIC        ("Leslie", "C"),
-- MAGIC        ("Liam", "C"),
-- MAGIC        ("Ravi", "S"),
-- MAGIC        ("Róisín", "S"),
-- MAGIC        ("Sam", "S"),
-- MAGIC        ("Shalini","C"),
-- MAGIC        ("Zuri", "S");
-- MAGIC ```
-- MAGIC
-- MAGIC 2. If you get a popup window asking you which compute resource to use, continue to use the **shared_warehouse** SQL warehouse.
-- MAGIC
-- MAGIC 2. Let's double-check that we haven't missed any sales reps, so as to be sure we don't introduce any nulls in our metric view. In the SQL Editor, enter and run this query, replacing `labuser` with the name of your assigned schema:
-- MAGIC
-- MAGIC ```
-- MAGIC USE CATALOG labuser ; -- replace with your catalog
-- MAGIC USE SCHEMA DEFAULT ;
-- MAGIC SELECT o.salesrep
-- MAGIC FROM dbacademy_australia.v01.orders o
-- MAGIC WHERE NOT EXISTS (SELECT 1 FROM methodologies m WHERE m.salesrep = o.salesrep);
-- MAGIC ```
-- MAGIC
-- MAGIC This query should return no rows.
-- MAGIC
-- MAGIC 3. Let's check Canada in the same way. In the SQL Editor, enter and run this query, replacing `labuser` with the name of your assigned schema:
-- MAGIC
-- MAGIC ```
-- MAGIC USE CATALOG labuser ; -- replace with your catalog
-- MAGIC USE SCHEMA DEFAULT ;
-- MAGIC SELECT o.salesrep
-- MAGIC FROM dbacademy_canada.v01.orders o
-- MAGIC WHERE NOT EXISTS (SELECT 1 FROM methodologies m WHERE m.salesrep = o.salesrep);
-- MAGIC ```
-- MAGIC
-- MAGIC This query should also return no rows.
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC
-- MAGIC ## F1. Create a Metric View for Australia Orders
-- MAGIC
-- MAGIC 1. In Catalog view, navigate to **dbacademy_australia.v01.orders**, the table to use as the fact table for our first metric view. Pull down the chevron in the **Create** button at top right to select Metric View. 
-- MAGIC
-- MAGIC 1. Use the dropdowns for catalog and schema at the top left of the panel to place the metric view you are building in the with name beginning with `labuser` and the **default** schema.
-- MAGIC
-- MAGIC 1. If the user interface brings up the Databricks Assistant chat window, close it for now.
-- MAGIC
-- MAGIC 1. Click on the proposed name of the metric view, which contains the name of the base table, and change it to **au_orders**.
-- MAGIC
-- MAGIC 1. You will see a skeletal metric view YAML file in the editor window, consisting of these sections:
-- MAGIC
-- MAGIC | Section | Meaning |
-- MAGIC |----|----|
-- MAGIC | **version** | Databricks's version of the metric-view specification |
-- MAGIC | **source** | the fact table for this metric view |
-- MAGIC
-- MAGIC **CAUTION**: If the user interface proposed sections for you other than these two, delete them for now. 
-- MAGIC
-- MAGIC The first line of the skeleton metric view should read
-- MAGIC
-- MAGIC ```
-- MAGIC version: 1.1
-- MAGIC ```
-- MAGIC
-- MAGIC If not, change the line so that it does.
-- MAGIC
-- MAGIC **NOTE**: The lab exercises in this course were designed to work with version 1.1 of the metric views API. If the sample metric view proposed for you by the user interface starts with a different number, Databricks has introduced a new version of the API since this course was released. However, specifying version 1.1 in your metric views in this course will ensure that the lab exercises continue to work as intended. 
-- MAGIC
-- MAGIC 6. The next line identifies the fact table you chose to build this metric view on:
-- MAGIC
-- MAGIC ```
-- MAGIC source: dbacademy_australia.v01.orders
-- MAGIC ```
-- MAGIC
-- MAGIC 7. If the UI proposed a number of sample dimensions and measures for you, delete them for now. Delete all the suggested measures by highlighting them and cutting.
-- MAGIC
-- MAGIC 8. Add a **joins** section with joins that bring in enriching data for the fact table. Insert the following below **source**, replacing `labuser` with the name of your catalog:
-- MAGIC
-- MAGIC ```
-- MAGIC joins:
-- MAGIC    - name: customers
-- MAGIC      source: dbacademy_australia.v01.customers
-- MAGIC      on: customers.customerid = source.customerid
-- MAGIC    - name: methodologies
-- MAGIC      source: labuser.default.methodologies
-- MAGIC      on: methodologies.salesrep = source.salesrep
-- MAGIC ```
-- MAGIC
-- MAGIC In the above, replace `labuser` with the name of your catalog. Make sure to get the indentation exactly as shown. Use spaces, not tabs.
-- MAGIC
-- MAGIC 9. Add a filter, so that we can reduce the cost of this metric view by limiting the number of rows it will return. Insert this line, without any indentation, just below the source section, above the **joins** keyword.
-- MAGIC
-- MAGIC ```
-- MAGIC filter: YEAR(source.orderdate) >= 2022
-- MAGIC ```
-- MAGIC
-- MAGIC 10. Now add some measures. Remember that a measure is an indicator of business activity, in terms our data consumers understand, independently of how that indicator is grouped or sliced. Insert a `measures:` keyword, on a new line at the end of the file, so that it comprises a new  **measures** section, and then some measure definitions:
-- MAGIC
-- MAGIC ```
-- MAGIC measures:
-- MAGIC   - name: total_items_sold
-- MAGIC     expr: COUNT(source.quantity)
-- MAGIC     display_name: Total Items Sold
-- MAGIC   - name: total_revenue
-- MAGIC     expr: SUM(source.orderamt)
-- MAGIC     display_name: Total Revenue
-- MAGIC
-- MAGIC ```
-- MAGIC
-- MAGIC 11. Now add some dimensions. Remember that a dimension is a way to slice or group the offered measures; the selection of dimensions is driven by the needs of the business. For example, if your data consumers make decisions based on quarterly data, you would choose to offer dimensions based on quarters. Insert a `dimensions:` keyword, on a new line at the end of the file, so that it comprises a new  **dimensions** section, and then some measure definitions:
-- MAGIC
-- MAGIC ```
-- MAGIC dimensions:
-- MAGIC   - name: orderid
-- MAGIC     expr: source.orderid
-- MAGIC     display_name: Order ID
-- MAGIC   - name: productid
-- MAGIC     expr: source.productid
-- MAGIC     display_name: Product ID
-- MAGIC   - name: order_date
-- MAGIC     expr: source.orderdate
-- MAGIC     display_name: Order Date
-- MAGIC   - name: order_year
-- MAGIC     expr: DATE(DATE_TRUNC('year',order_date))
-- MAGIC     display_name: Order Year
-- MAGIC   - name: order_quarter
-- MAGIC     expr: QUARTER(order_date)
-- MAGIC     display_name: Order Year
-- MAGIC   - name: methodology
-- MAGIC     expr: methodologies.method
-- MAGIC     display_name: Sales Methodology
-- MAGIC   - name: customer_id
-- MAGIC     expr: source.customerid
-- MAGIC     display_name: Customer ID
-- MAGIC   - name: customer_name
-- MAGIC     expr: customers.customername
-- MAGIC     display_name: Customer Name
-- MAGIC ``` 
-- MAGIC
-- MAGIC 12. Now click **Create** at top right. If the UI points out any syntax errors, correct them and try again.
-- MAGIC
-- MAGIC 1. Stay in the metric view editor.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## F2. Add window measures to the metric view
-- MAGIC
-- MAGIC While still in the metric view editor, add a windowed measure that shows a year-over-year comparison of revenue, as well as quarter-to date revenue.
-- MAGIC
-- MAGIC 1. First let's implement the year-over-year comparison. Append the following to the **measures** section:
-- MAGIC
-- MAGIC ```
-- MAGIC   - name: current_year_revenue
-- MAGIC     expr: MEASURE(total_revenue)
-- MAGIC     display_name: Current Year Revenue
-- MAGIC     window:
-- MAGIC       - order: order_year
-- MAGIC         range: current
-- MAGIC         semiadditive: last
-- MAGIC   - name: previous_year_revenue
-- MAGIC     expr: MEASURE(total_revenue)
-- MAGIC     display_name: Previous Year Revenue
-- MAGIC     window:
-- MAGIC       - order: order_year
-- MAGIC         range: trailing 1 year
-- MAGIC         semiadditive: last
-- MAGIC   - name: yoy_growth_pct
-- MAGIC     expr: |
-- MAGIC       (MEASURE(current_year_revenue) - MEASURE(previous_year_revenue)) /
-- MAGIC       MEASURE(previous_year_revenue)
-- MAGIC     display_name: YoY Growth (%)
-- MAGIC     format:
-- MAGIC       type: percentage
-- MAGIC       decimal_places:
-- MAGIC         type: exact
-- MAGIC         places: 2
-- MAGIC ```
-- MAGIC
-- MAGIC 2. Now let's implement the quarter-to-date comparison. Append the following to the **measures** section:
-- MAGIC
-- MAGIC ```
-- MAGIC   - name: qtd_revenue
-- MAGIC     expr: SUM(source.orderamt)
-- MAGIC     display_name: Quarter-To-Date Revenue
-- MAGIC     window:
-- MAGIC       - order: order_date
-- MAGIC         range: cumulative
-- MAGIC         semiadditive: last
-- MAGIC       - order: order_quarter
-- MAGIC         range: current
-- MAGIC         semiadditive: last
-- MAGIC ```
-- MAGIC
-- MAGIC 3. Now click **Create** at top right. If the UI points out any syntax errors, correct them and try again.
-- MAGIC
-- MAGIC 1. When prompted, click **Keep editing** to stay in the metric view editor.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## F3. Save the metric view definition to a temporary file
-- MAGIC
-- MAGIC **CAUTION**: Before you proceed, confirm that your metric view has six measures and six dimensions. 
-- MAGIC
-- MAGIC * Dimensions:
-- MAGIC   *  orderid
-- MAGIC   *  order_date
-- MAGIC   * order_year
-- MAGIC   * order_quarter
-- MAGIC   *  productid
-- MAGIC   *  methodology
-- MAGIC   * customer_id
-- MAGIC   * customer_name
-- MAGIC * Measures:
-- MAGIC   * total_items_sold
-- MAGIC   * total_revenue
-- MAGIC   * qtd_revenue
-- MAGIC   * current_year_revenue
-- MAGIC   * previous_year_revenue
-- MAGIC   * yoy_growth_pct
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC 1. Use your browser to highlight and then copy the entire YAML definition. 
-- MAGIC
-- MAGIC 1. Open a text editor on your laptop or desktop and paste in the YAML. 
-- MAGIC
-- MAGIC 1. Leave this window open and return to the Databricks UI window.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### F4. Create a metric view for Canada orders
-- MAGIC
-- MAGIC 1. Return to the metric view editor window for your Australia metric view. In the top right, click **Save**. 
-- MAGIC
-- MAGIC 1. In Catalog view, navigate to **dbacademy_canada.v01.orders**, the table to use as the fact table for our second metric view. Pull down the chevron in the **Create** button at top right to select Metric View. 
-- MAGIC
-- MAGIC 1. Use the dropdowns for catalog and schema at the top left of the panel to place the metric view you are building in the with name beginning with labuser and the default schema.
-- MAGIC
-- MAGIC 1. If the user interface brings up the Databricks Assistant chat window, close it for now.
-- MAGIC
-- MAGIC 1. Click on the proposed name of the metric view, which contains the name of the base table, and change it to **ca_orders**.
-- MAGIC
-- MAGIC 1. Paste the YAML from your other window for the **au_orders** metric view and change the catalog name to **dbacademy_canada**.
-- MAGIC
-- MAGIC 1. Delete the original ``version`` and ``source`` lines.
-- MAGIC
-- MAGIC 1. Confirm that the new metric view has ``version`` and ``source`` lines at top that look like this:
-- MAGIC
-- MAGIC ```
-- MAGIC version: 1.1
-- MAGIC source: dbacademy_canada.v01.orders
-- MAGIC ```
-- MAGIC
-- MAGIC 9. In the top right, click **Save**.
-- MAGIC
-- MAGIC
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## G. Create a dashboard displaying the metric views' results
-- MAGIC
-- MAGIC AI/BI Dashboards are the primary way to present a suite of business metrics to data consumers. 
-- MAGIC
-- MAGIC 1. In the Databricks UI, choose **Dashboards** from the left navigation, then click **Create dashboard** at top right. 
-- MAGIC
-- MAGIC 1. Click on the automatically generated name of the dashboard  and rename it to something that describes its business value, such as `Australia and Canada Sales KPIs`.
-- MAGIC
-- MAGIC 1. The next step is to define the data sources for our dashboard. Click the **Data** tab. 
-- MAGIC
-- MAGIC 1. We have three choices: **Create from SQL**, **Add data source**, or **Upload file**. Here, "data source" means table, view, or any queryable entity. Choose **Add data source**; click the Metric Views button, and click on your Australia metric view's fully-qualified, three-part name.
-- MAGIC
-- MAGIC
-- MAGIC 1. Now click on **Add another data source** and follow the same steps to point to your Canada metric view's fully-qualified, three-part name.
-- MAGIC
-- MAGIC 1. Now click on the presently empty canvas page called **Untitled Page**. Use the kebab menu next to that placeholder name to something useful: "Sales insights."
-- MAGIC
-- MAGIC 1. Because this dashboard needs to be self-explanatory for its non-technical consumers, add a title to the top of the dashboard. In the palette at the bottom of the display, click the icon for a text field, the T in a box, and drag and stretch the resulting box until it covers a headline. These text fields use Markdown formatting. To add a title, click in the box and type
-- MAGIC
-- MAGIC
-- MAGIC ```
-- MAGIC # Australia and Canada Sales KPIs
-- MAGIC ## data after 2021
-- MAGIC ```
-- MAGIC
-- MAGIC
-- MAGIC Clicking outside the box previews its contents.
-- MAGIC
-- MAGIC 8. Now add a variety of visualizations based on the metric view we created. First, add a bar chart for Australia sales year-over-year just below the dashboard title and on the right. Click on the visualization icon in the palette and locate a space for a  bar chart just underneath the headline. Now we click inside the newly laid-out widget, and  we can use the configuration panel at the far right of the screen to populate this widget.
-- MAGIC
-- MAGIC 1. Confirm that the selected dataset is **au_orders**.
-- MAGIC
-- MAGIC 1. Use the Visualization type pulldown to change its type to Bar. The X axis should be the order year. click the **+** icon for X axis and choose the Order Date dimension. Now we have bars, one for each month of data, but the dashboard doesn't know how high to make the bars. To achieve that, we have to work with the Y axis.
-- MAGIC
-- MAGIC 11. Click the **+** icon for the Y axis and choose the **YoY Growth (%)** field.
-- MAGIC
-- MAGIC 1. Still in the configuration panel, check the box at top for Widget Title. Then click on the placeholder text "Widget title" in the widget itself and replace it with `Year over Year Growth`.
-- MAGIC
-- MAGIC 1. Repeat the process to add a Canada sales year-over-year at right from the the **ca_orders** data source instead of the the **au_orders** data source. 
-- MAGIC
-- MAGIC 1. Now let's evaluate the sales reps' sales methodologies using pie charts. Click the visualization icon in the palette, at the bottom of the display, and land the widget at lower left. 
-- MAGIC
-- MAGIC 1. Use the right-side configuration panel to set its type to Pie. 
-- MAGIC
-- MAGIC 1. Confirm that the selected dataset is **au_orders**
-- MAGIC
-- MAGIC 1. Now define how each piece of the pie, which the user interface calls Angle, has its size computed. Click the **+** icon for **Angle** and choose **total_revenue**. 
-- MAGIC
-- MAGIC 1. To make distinct sections of the pie visible, change the color of each angle based on the **methodology** field. Click the **+** icon for Color and set it to **methodology**.
-- MAGIC
-- MAGIC 1. Repeat the process to add a Canada sales methodology comparison at right from the the **ca_orders** data source instead of the the **au_orders** data source. Your dashboard should now have four charts: two bar charts at top, with Australia on the left and Canada on the right; and two pie charts at bottom, again with Australia on the left and Canada on the right.
-- MAGIC
-- MAGIC How would you evaluate the two sales methodologies?
-- MAGIC
-- MAGIC **NOTE**: To expose this dashboard to users in your account, you would click the **Publish** button at top right. In this lab activity, there is no need to do so. Databricks Academy offers other training on how to build and maintain dashboards.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## H. Create an alert based on a metric view
-- MAGIC
-- MAGIC Alerts are a tool for your data consumers to get notified proactively based on business intelligence. What happens if orders drop, returns rise, or the discounts your salespeople grant rise above a certain threshold? 
-- MAGIC
-- MAGIC Typically business data consumers care about real-time notifications. Because the current data set is historical rather than current, we'll create an alert for our metric view that would be of interest to data engineers. Recall that all joins defined in metric views are LEFT JOINs, which means they can introduce nulls if foreign keys in the fact table are unmatched. Let's create a query that would be meaningful for weekly runs.
-- MAGIC
-- MAGIC 1. Choose **Alerts** from the left navigation of the Databricks UI. In the resulting screen click **Create alert**. The first step is to compose and save a SQL query that queries the metric view for all orders generated in the last week with an unmatched **customer_id**. Enter the following query, replacing `labuser` with the name of your catalog:
-- MAGIC
-- MAGIC ```
-- MAGIC SELECT distinct customer_id FROM labuser12662960.default.au_orders -- replace with the name of your catalog
-- MAGIC WHERE customer_name IS NULL; 
-- MAGIC ```
-- MAGIC
-- MAGIC 2. Click the Run button to confirm that the query works. It should return no rows.
-- MAGIC
-- MAGIC 3. We want our alert to fire if this query returns any rows at all. In the condition section, choose **COUNT** as our aggregation and the field it should be looking at as **customer_id**. For the operator choose **>** (greater than) and for the comparison choose **Static Value** and **0**.
-- MAGIC
-- MAGIC 1. Click the **Test condition** button. The Databricks UI tests the condition and confirms that it will not fire.
-- MAGIC
-- MAGIC 1. Enter yourself as the recipient in **Notify** section. Your username in the Vocareum lab environment probably begins with `labuser`. Type in `labuser` and accept the autocompletion. 
-- MAGIC
-- MAGIC 1. Click **View alert**. The resulting screen is a summary.
-- MAGIC
-- MAGIC 1. Click the **Schedule** button at top right. Accept the default schedule and click **Save**.
-- MAGIC
-- MAGIC Now our metric view is being health-checked regularly.
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## I. Interact with Genie using the metric view as a source
-- MAGIC
-- MAGIC Genie spaces are well-suited for publication to your data consumers because they offer management controls. 
-- MAGIC
-- MAGIC 1. In the left-hand menu of the Databricks UI choose **Genie**. Then click the **New** button at top left. 
-- MAGIC
-- MAGIC 1. Next the UI asks us what we want our Genie space's data source to be. Click the Metric Views button, and click on your Australia metric view's fully-qualified, three-part name.
-- MAGIC
-- MAGIC 1. Click **Create**.
-- MAGIC
-- MAGIC 1. Notice that the Genie engine harvests the measures and dimensions from the metric view definition to suggest sample questions. You can add more sample questions. 
-- MAGIC
-- MAGIC 1. In the right-side panel, click **Data** then the **Add** button to bring in the `ca_orders` metric view as well.
-- MAGIC
-- MAGIC 1. The Genie engine will also consult the queries you (and, in a real Databricks deployment, your coworkers) and suggest them for addition to the space too. If Genie offers to add one or more queries to the workspace, allow it.
-- MAGIC
-- MAGIC 1. Experiment with the sample questions offered. Notice that Genie tries to give both tabular and graphical responses to questions.
-- MAGIC
-- MAGIC 1. Try asking natural language questions about the data. 
-- MAGIC
-- MAGIC 1. In a real Databricks deployment, you would click the **Share** button at top right to publish the Genie space to users, with permission controls governed by Unity Catalog.
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Additional Resources
-- MAGIC
-- MAGIC - [Composability in metric views](https://docs.databricks.com/aws/en/metric-views/data-modeling/composability) 
-- MAGIC - [Use window measures](https://docs.databricks.com/aws/en/metric-views/window-measures) 
-- MAGIC

-- COMMAND ----------

-- MAGIC %md
-- MAGIC &copy; 2026 Databricks, Inc. All rights reserved. Apache, Apache Spark, Spark, the Spark Logo, Apache Iceberg, Iceberg, and the Apache Iceberg logo are trademarks of the <a href="https://www.apache.org/" target="_blank">Apache Software Foundation</a>.<br/><br/><a href="https://databricks.com/privacy-policy" target="_blank">Privacy Policy</a> | <a href="https://databricks.com/terms-of-use" target="_blank">Terms of Use</a> | <a href="https://help.databricks.com/" target="_blank">Support</a>
